### ISSUE TITLE
Newsletter Plugin Not Mobile Friendly

### ISSUE THREAD

**Issue by theentreprenew** [hizzle-co/noptin#96]
**Describe the bug**
I'm using the Noptin newsletter plugin version 1.3.4 on Wordpress version 5.5.1. The plugin works great on desktop as in screenshot below. On mobile however the subscription form is out of sync.

**To Reproduce**
1. Go to https://myangu.com on both desktop and on mobile

**Expected behavior**
The email slot should be clearly visible but on mobile the submit button covers it.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome Browser
 - Version 85.0.4183.102

**Smartphone (please complete the following information):**
 - Samsung Note 4
 - Chrome Browser
![_20200923_212827](https://user-images.githubusercontent.com/12426115/94061557-d7ea0e00-fde5-11ea-96b6-eed648b4f097.JPG)
![_20200923_212808](https://user-images.githubusercontent.com/12426115/94061569-d91b3b00-fde5-11ea-8dd8-011bc2e15235.JPG)

**Comment by picocodes** [comment]
Hello,

This has been fixed. For now, replace the custom css on that form with this.

```css
/*Custom css*/

.noptin-optin-form-wrapper .noptin-form-single-line .noptin-form-fields{
 	position: relative;
}

.noptin-optin-form-wrapper .noptin-optin-form.noptin-form-single-line .noptin-form-submit{
	border-radius: 30px;
}

@media only screen and (min-width: 768px) {

	.noptin-optin-form-wrapper .noptin-optin-form.noptin-form-single-line .noptin-form-submit{
		position: absolute;
		bottom: -1px;
		top: 0;
		right: 0px;
	}

}

.noptin-optin-form-wrapper .noptin-form-single-line .noptin-form-field{
 	border-radius: 30px !important;
	border: none !important;
}
```
